<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>VIVIDIA</AssemblyName>
    <Product>VIVIDIA</Product>
    <AssemblyTitle>VIVIDIA</AssemblyTitle>
    <Company>zeddo-dev</Company>
    <Version>1.0.0</Version>
    <FileVersion>1.0.0.0</FileVersion>
    <InformationalVersion>1.0</InformationalVersion>
  </PropertyGroup>

  <PropertyGroup Condition="Exists('$(MSBuildProjectDirectory)/../../assets/vividia.ico')">
    <ApplicationIcon>$(MSBuildProjectDirectory)/../../assets/vividia.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup Condition="Exists('$(MSBuildProjectDirectory)/../../assets/mark.png')">
    <EmbeddedResource Include="$(MSBuildProjectDirectory)/../../assets/mark.png" LogicalName="Vividia.mark.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NvAPIWrapper.Net" Version="0.8.1.101" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SelfTest" />
  </ItemGroup>

</Project>
